/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type VPStatusStruct = {
  state: PromiseOrValue<BigNumberish>;
  allowedVerifiers: PromiseOrValue<string>[];
  finalVerifier: PromiseOrValue<string>;
  valid: PromiseOrValue<boolean>;
  rat: PromiseOrValue<BigNumberish>;
  uat: PromiseOrValue<BigNumberish>;
  exp: PromiseOrValue<BigNumberish>;
  nbf: PromiseOrValue<BigNumberish>;
};

export type VPStatusStructOutput = [
  number,
  string[],
  string,
  boolean,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  state: number;
  allowedVerifiers: string[];
  finalVerifier: string;
  valid: boolean;
  rat: BigNumber;
  uat: BigNumber;
  exp: BigNumber;
  nbf: BigNumber;
};

export interface VPRegistryInterface extends utils.Interface {
  functions: {
    "cancel(bytes32)": FunctionFragment;
    "consumed(bytes32)": FunctionFragment;
    "getStatus(bytes32,uint256)": FunctionFragment;
    "initialize()": FunctionFragment;
    "presented(bytes32)": FunctionFragment;
    "register(bytes32,address[10],uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cancel"
      | "consumed"
      | "getStatus"
      | "initialize"
      | "presented"
      | "register"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancel",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "consumed",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatus",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presented",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "consumed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "presented", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;

  events: {
    "Consumed(bytes32,address)": EventFragment;
    "HashValid(bytes32,bool)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "NoStoragePolicy(bytes32,address,bytes32,bytes15)": EventFragment;
    "Presented(bytes32,address)": EventFragment;
    "Registered(bytes32,address,address[10])": EventFragment;
    "StatusChanged(bytes32,uint8,uint8,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Consumed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HashValid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NoStoragePolicy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Presented"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Registered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StatusChanged"): EventFragment;
}

export interface ConsumedEventObject {
  vpHash: string;
  verifier: string;
}
export type ConsumedEvent = TypedEvent<[string, string], ConsumedEventObject>;

export type ConsumedEventFilter = TypedEventFilter<ConsumedEvent>;

export interface HashValidEventObject {
  vpHash: string;
  valid: boolean;
}
export type HashValidEvent = TypedEvent<
  [string, boolean],
  HashValidEventObject
>;

export type HashValidEventFilter = TypedEventFilter<HashValidEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface NoStoragePolicyEventObject {
  vpHash: string;
  verifier: string;
  message0: string;
  message1: string;
}
export type NoStoragePolicyEvent = TypedEvent<
  [string, string, string, string],
  NoStoragePolicyEventObject
>;

export type NoStoragePolicyEventFilter = TypedEventFilter<NoStoragePolicyEvent>;

export interface PresentedEventObject {
  vpHash: string;
  verifier: string;
}
export type PresentedEvent = TypedEvent<[string, string], PresentedEventObject>;

export type PresentedEventFilter = TypedEventFilter<PresentedEvent>;

export interface RegisteredEventObject {
  vpHash: string;
  from: string;
  to: string[];
}
export type RegisteredEvent = TypedEvent<
  [string, string, string[]],
  RegisteredEventObject
>;

export type RegisteredEventFilter = TypedEventFilter<RegisteredEvent>;

export interface StatusChangedEventObject {
  vpHash: string;
  prevState: number;
  actualState: number;
  reason: string;
}
export type StatusChangedEvent = TypedEvent<
  [string, number, number, string],
  StatusChangedEventObject
>;

export type StatusChangedEventFilter = TypedEventFilter<StatusChangedEvent>;

export interface VPRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VPRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancel(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    consumed(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getStatus(
      vpHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, VPStatusStructOutput] & {
        found: boolean;
        status: VPStatusStructOutput;
      }
    >;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    presented(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    register(
      vpHash: PromiseOrValue<BytesLike>,
      allowedVerifiers: PromiseOrValue<string>[],
      exp: PromiseOrValue<BigNumberish>,
      nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  cancel(
    vpHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  consumed(
    vpHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getStatus(
    vpHash: PromiseOrValue<BytesLike>,
    extTimestamp: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [boolean, VPStatusStructOutput] & {
      found: boolean;
      status: VPStatusStructOutput;
    }
  >;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  presented(
    vpHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  register(
    vpHash: PromiseOrValue<BytesLike>,
    allowedVerifiers: PromiseOrValue<string>[],
    exp: PromiseOrValue<BigNumberish>,
    nbf: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cancel(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    consumed(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    getStatus(
      vpHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, VPStatusStructOutput] & {
        found: boolean;
        status: VPStatusStructOutput;
      }
    >;

    initialize(overrides?: CallOverrides): Promise<void>;

    presented(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    register(
      vpHash: PromiseOrValue<BytesLike>,
      allowedVerifiers: PromiseOrValue<string>[],
      exp: PromiseOrValue<BigNumberish>,
      nbf: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Consumed(bytes32,address)"(
      vpHash?: PromiseOrValue<BytesLike> | null,
      verifier?: PromiseOrValue<string> | null
    ): ConsumedEventFilter;
    Consumed(
      vpHash?: PromiseOrValue<BytesLike> | null,
      verifier?: PromiseOrValue<string> | null
    ): ConsumedEventFilter;

    "HashValid(bytes32,bool)"(
      vpHash?: PromiseOrValue<BytesLike> | null,
      valid?: PromiseOrValue<boolean> | null
    ): HashValidEventFilter;
    HashValid(
      vpHash?: PromiseOrValue<BytesLike> | null,
      valid?: PromiseOrValue<boolean> | null
    ): HashValidEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "NoStoragePolicy(bytes32,address,bytes32,bytes15)"(
      vpHash?: PromiseOrValue<BytesLike> | null,
      verifier?: PromiseOrValue<string> | null,
      message0?: null,
      message1?: null
    ): NoStoragePolicyEventFilter;
    NoStoragePolicy(
      vpHash?: PromiseOrValue<BytesLike> | null,
      verifier?: PromiseOrValue<string> | null,
      message0?: null,
      message1?: null
    ): NoStoragePolicyEventFilter;

    "Presented(bytes32,address)"(
      vpHash?: PromiseOrValue<BytesLike> | null,
      verifier?: PromiseOrValue<string> | null
    ): PresentedEventFilter;
    Presented(
      vpHash?: PromiseOrValue<BytesLike> | null,
      verifier?: PromiseOrValue<string> | null
    ): PresentedEventFilter;

    "Registered(bytes32,address,address[10])"(
      vpHash?: PromiseOrValue<BytesLike> | null,
      from?: PromiseOrValue<string> | null,
      to?: null
    ): RegisteredEventFilter;
    Registered(
      vpHash?: PromiseOrValue<BytesLike> | null,
      from?: PromiseOrValue<string> | null,
      to?: null
    ): RegisteredEventFilter;

    "StatusChanged(bytes32,uint8,uint8,bytes32)"(
      vpHash?: PromiseOrValue<BytesLike> | null,
      prevState?: PromiseOrValue<BigNumberish> | null,
      actualState?: PromiseOrValue<BigNumberish> | null,
      reason?: null
    ): StatusChangedEventFilter;
    StatusChanged(
      vpHash?: PromiseOrValue<BytesLike> | null,
      prevState?: PromiseOrValue<BigNumberish> | null,
      actualState?: PromiseOrValue<BigNumberish> | null,
      reason?: null
    ): StatusChangedEventFilter;
  };

  estimateGas: {
    cancel(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    consumed(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getStatus(
      vpHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    presented(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    register(
      vpHash: PromiseOrValue<BytesLike>,
      allowedVerifiers: PromiseOrValue<string>[],
      exp: PromiseOrValue<BigNumberish>,
      nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cancel(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    consumed(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getStatus(
      vpHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    presented(
      vpHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    register(
      vpHash: PromiseOrValue<BytesLike>,
      allowedVerifiers: PromiseOrValue<string>[],
      exp: PromiseOrValue<BigNumberish>,
      nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
