/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IVCRegistryInterface extends utils.Interface {
  functions: {
    "addIssuer(address)": FunctionFragment;
    "getStateByHash(bytes32,uint256)": FunctionFragment;
    "getStateById(bytes,uint256)": FunctionFragment;
    "getStatusByHash(bytes32,uint256)": FunctionFragment;
    "getStatusById(bytes,uint256)": FunctionFragment;
    "initialize(address[])": FunctionFragment;
    "isCxcIssuer(address)": FunctionFragment;
    "register(bytes,bytes32,uint256,uint256)": FunctionFragment;
    "registerList(bytes[],bytes32[],uint256[],uint256[])": FunctionFragment;
    "registerOnlyHash(bytes32,uint256,uint256)": FunctionFragment;
    "revokeByHash(bytes32,string)": FunctionFragment;
    "revokeById(bytes,string)": FunctionFragment;
    "revokeListByHash(bytes32[],string[])": FunctionFragment;
    "revokeListById(bytes[],string[])": FunctionFragment;
    "updateByHash(bytes32,uint256,uint256)": FunctionFragment;
    "updateById(bytes,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addIssuer"
      | "getStateByHash"
      | "getStateById"
      | "getStatusByHash"
      | "getStatusById"
      | "initialize"
      | "isCxcIssuer"
      | "register"
      | "registerList"
      | "registerOnlyHash"
      | "revokeByHash"
      | "revokeById"
      | "revokeListByHash"
      | "revokeListById"
      | "updateByHash"
      | "updateById"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addIssuer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateByHash",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateById",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatusByHash",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatusById",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isCxcIssuer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerList",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOnlyHash",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeByHash",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeById",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeListByHash",
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeListById",
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateByHash",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateById",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "addIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStateByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatusByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatusById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCxcIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOnlyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeById", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeListByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeListById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateById", data: BytesLike): Result;

  events: {
    "IdAdded(bytes32,bytes32)": EventFragment;
    "Registered(bytes32,bytes32,address)": EventFragment;
    "Revoked(bytes32,bytes32)": EventFragment;
    "StatusChanged(bytes32,bytes32,uint8,uint8,string)": EventFragment;
    "Updated(bytes32,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "IdAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Registered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Revoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StatusChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Updated"): EventFragment;
}

export interface IdAddedEventObject {
  vcIdHash: string;
  vcHash: string;
}
export type IdAddedEvent = TypedEvent<[string, string], IdAddedEventObject>;

export type IdAddedEventFilter = TypedEventFilter<IdAddedEvent>;

export interface RegisteredEventObject {
  vcIdHash: string;
  vcHash: string;
  byIssuer: string;
}
export type RegisteredEvent = TypedEvent<
  [string, string, string],
  RegisteredEventObject
>;

export type RegisteredEventFilter = TypedEventFilter<RegisteredEvent>;

export interface RevokedEventObject {
  vcIdHash: string;
  vcHash: string;
}
export type RevokedEvent = TypedEvent<[string, string], RevokedEventObject>;

export type RevokedEventFilter = TypedEventFilter<RevokedEvent>;

export interface StatusChangedEventObject {
  vcIdHash: string;
  vcHash: string;
  prevState: number;
  actualState: number;
  reason: string;
}
export type StatusChangedEvent = TypedEvent<
  [string, string, number, number, string],
  StatusChangedEventObject
>;

export type StatusChangedEventFilter = TypedEventFilter<StatusChangedEvent>;

export interface UpdatedEventObject {
  vcIdHash: string;
  vcHash: string;
}
export type UpdatedEvent = TypedEvent<[string, string], UpdatedEventObject>;

export type UpdatedEventFilter = TypedEventFilter<UpdatedEvent>;

export interface IVCRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IVCRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addIssuer(
      _newIssuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getStateByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { _found: boolean; _state: string }>;

    getStateById(
      _vcId: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { _found: boolean; _state: string }>;

    getStatusByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        _found: boolean;
        _state: string;
        _rat: BigNumber;
        _uat: BigNumber;
        _ext: BigNumber;
        _nbf: BigNumber;
      }
    >;

    getStatusById(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        _found: boolean;
        _state: string;
        _rat: BigNumber;
        _uat: BigNumber;
        _ext: BigNumber;
        _nbf: BigNumber;
      }
    >;

    initialize(
      _issuers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isCxcIssuer(
      issuer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    register(
      _id: PromiseOrValue<BytesLike>,
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerList(
      ids: PromiseOrValue<BytesLike>[],
      _vcHashes: PromiseOrValue<BytesLike>[],
      _exp: PromiseOrValue<BigNumberish>[],
      _nbf: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerOnlyHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeById(
      _vcId: PromiseOrValue<BytesLike>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeListByHash(
      _vcHashes: PromiseOrValue<BytesLike>[],
      _reasons: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeListById(
      _vcIds: PromiseOrValue<BytesLike>[],
      _reasons: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateById(
      _vcId: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addIssuer(
    _newIssuer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getStateByHash(
    _vcHash: PromiseOrValue<BytesLike>,
    extTimestamp: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { _found: boolean; _state: string }>;

  getStateById(
    _vcId: PromiseOrValue<BytesLike>,
    extTimestamp: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { _found: boolean; _state: string }>;

  getStatusByHash(
    _vcHash: PromiseOrValue<BytesLike>,
    extTimestamp: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      _found: boolean;
      _state: string;
      _rat: BigNumber;
      _uat: BigNumber;
      _ext: BigNumber;
      _nbf: BigNumber;
    }
  >;

  getStatusById(
    _vcHash: PromiseOrValue<BytesLike>,
    extTimestamp: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      _found: boolean;
      _state: string;
      _rat: BigNumber;
      _uat: BigNumber;
      _ext: BigNumber;
      _nbf: BigNumber;
    }
  >;

  initialize(
    _issuers: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isCxcIssuer(
    issuer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  register(
    _id: PromiseOrValue<BytesLike>,
    _vcHash: PromiseOrValue<BytesLike>,
    _exp: PromiseOrValue<BigNumberish>,
    _nbf: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerList(
    ids: PromiseOrValue<BytesLike>[],
    _vcHashes: PromiseOrValue<BytesLike>[],
    _exp: PromiseOrValue<BigNumberish>[],
    _nbf: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerOnlyHash(
    _vcHash: PromiseOrValue<BytesLike>,
    _exp: PromiseOrValue<BigNumberish>,
    _nbf: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeByHash(
    _vcHash: PromiseOrValue<BytesLike>,
    _reason: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeById(
    _vcId: PromiseOrValue<BytesLike>,
    _reason: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeListByHash(
    _vcHashes: PromiseOrValue<BytesLike>[],
    _reasons: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeListById(
    _vcIds: PromiseOrValue<BytesLike>[],
    _reasons: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateByHash(
    _vcHash: PromiseOrValue<BytesLike>,
    _exp: PromiseOrValue<BigNumberish>,
    _nbf: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateById(
    _vcId: PromiseOrValue<BytesLike>,
    _exp: PromiseOrValue<BigNumberish>,
    _nbf: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addIssuer(
      _newIssuer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getStateByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { _found: boolean; _state: string }>;

    getStateById(
      _vcId: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { _found: boolean; _state: string }>;

    getStatusByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        _found: boolean;
        _state: string;
        _rat: BigNumber;
        _uat: BigNumber;
        _ext: BigNumber;
        _nbf: BigNumber;
      }
    >;

    getStatusById(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        _found: boolean;
        _state: string;
        _rat: BigNumber;
        _uat: BigNumber;
        _ext: BigNumber;
        _nbf: BigNumber;
      }
    >;

    initialize(
      _issuers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    isCxcIssuer(
      issuer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    register(
      _id: PromiseOrValue<BytesLike>,
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerList(
      ids: PromiseOrValue<BytesLike>[],
      _vcHashes: PromiseOrValue<BytesLike>[],
      _exp: PromiseOrValue<BigNumberish>[],
      _nbf: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    registerOnlyHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _reason: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeById(
      _vcId: PromiseOrValue<BytesLike>,
      _reason: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeListByHash(
      _vcHashes: PromiseOrValue<BytesLike>[],
      _reasons: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    revokeListById(
      _vcIds: PromiseOrValue<BytesLike>[],
      _reasons: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    updateByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateById(
      _vcId: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "IdAdded(bytes32,bytes32)"(
      vcIdHash?: PromiseOrValue<BytesLike> | null,
      vcHash?: PromiseOrValue<BytesLike> | null
    ): IdAddedEventFilter;
    IdAdded(
      vcIdHash?: PromiseOrValue<BytesLike> | null,
      vcHash?: PromiseOrValue<BytesLike> | null
    ): IdAddedEventFilter;

    "Registered(bytes32,bytes32,address)"(
      vcIdHash?: PromiseOrValue<BytesLike> | null,
      vcHash?: PromiseOrValue<BytesLike> | null,
      byIssuer?: PromiseOrValue<string> | null
    ): RegisteredEventFilter;
    Registered(
      vcIdHash?: PromiseOrValue<BytesLike> | null,
      vcHash?: PromiseOrValue<BytesLike> | null,
      byIssuer?: PromiseOrValue<string> | null
    ): RegisteredEventFilter;

    "Revoked(bytes32,bytes32)"(
      vcIdHash?: PromiseOrValue<BytesLike> | null,
      vcHash?: PromiseOrValue<BytesLike> | null
    ): RevokedEventFilter;
    Revoked(
      vcIdHash?: PromiseOrValue<BytesLike> | null,
      vcHash?: PromiseOrValue<BytesLike> | null
    ): RevokedEventFilter;

    "StatusChanged(bytes32,bytes32,uint8,uint8,string)"(
      vcIdHash?: null,
      vcHash?: PromiseOrValue<BytesLike> | null,
      prevState?: PromiseOrValue<BigNumberish> | null,
      actualState?: PromiseOrValue<BigNumberish> | null,
      reason?: null
    ): StatusChangedEventFilter;
    StatusChanged(
      vcIdHash?: null,
      vcHash?: PromiseOrValue<BytesLike> | null,
      prevState?: PromiseOrValue<BigNumberish> | null,
      actualState?: PromiseOrValue<BigNumberish> | null,
      reason?: null
    ): StatusChangedEventFilter;

    "Updated(bytes32,bytes32)"(
      vcIdHash?: PromiseOrValue<BytesLike> | null,
      vcHash?: PromiseOrValue<BytesLike> | null
    ): UpdatedEventFilter;
    Updated(
      vcIdHash?: PromiseOrValue<BytesLike> | null,
      vcHash?: PromiseOrValue<BytesLike> | null
    ): UpdatedEventFilter;
  };

  estimateGas: {
    addIssuer(
      _newIssuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getStateByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStateById(
      _vcId: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStatusByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStatusById(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _issuers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isCxcIssuer(
      issuer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    register(
      _id: PromiseOrValue<BytesLike>,
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerList(
      ids: PromiseOrValue<BytesLike>[],
      _vcHashes: PromiseOrValue<BytesLike>[],
      _exp: PromiseOrValue<BigNumberish>[],
      _nbf: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerOnlyHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeById(
      _vcId: PromiseOrValue<BytesLike>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeListByHash(
      _vcHashes: PromiseOrValue<BytesLike>[],
      _reasons: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeListById(
      _vcIds: PromiseOrValue<BytesLike>[],
      _reasons: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateById(
      _vcId: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addIssuer(
      _newIssuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getStateByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStateById(
      _vcId: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStatusByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStatusById(
      _vcHash: PromiseOrValue<BytesLike>,
      extTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _issuers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isCxcIssuer(
      issuer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    register(
      _id: PromiseOrValue<BytesLike>,
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerList(
      ids: PromiseOrValue<BytesLike>[],
      _vcHashes: PromiseOrValue<BytesLike>[],
      _exp: PromiseOrValue<BigNumberish>[],
      _nbf: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerOnlyHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeById(
      _vcId: PromiseOrValue<BytesLike>,
      _reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeListByHash(
      _vcHashes: PromiseOrValue<BytesLike>[],
      _reasons: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeListById(
      _vcIds: PromiseOrValue<BytesLike>[],
      _reasons: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateByHash(
      _vcHash: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateById(
      _vcId: PromiseOrValue<BytesLike>,
      _exp: PromiseOrValue<BigNumberish>,
      _nbf: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
