/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as external from "./external";
export * as interfaces from "./interfaces";
export { VCRegistry__factory } from "./VCRegistry__factory";
export { VPRegistry__factory } from "./VPRegistry__factory";
