/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVCRegistry__factory } from "./IVCRegistry__factory";
export { IVPRegistry__factory } from "./IVPRegistry__factory";
