/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVCRegistry,
  IVCRegistryInterface,
} from "../../../contracts/interfaces/IVCRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "vcIdHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "vcHash",
        type: "bytes32",
      },
    ],
    name: "IdAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "vcIdHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "vcHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "byIssuer",
        type: "address",
      },
    ],
    name: "Registered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "vcIdHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "vcHash",
        type: "bytes32",
      },
    ],
    name: "Revoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "vcIdHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "vcHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "enum States",
        name: "prevState",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "enum States",
        name: "actualState",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "StatusChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "vcIdHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "vcHash",
        type: "bytes32",
      },
    ],
    name: "Updated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newIssuer",
        type: "address",
      },
    ],
    name: "addIssuer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_vcHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "extTimestamp",
        type: "uint256",
      },
    ],
    name: "getStateByHash",
    outputs: [
      {
        internalType: "bool",
        name: "_found",
        type: "bool",
      },
      {
        internalType: "string",
        name: "_state",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_vcId",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "extTimestamp",
        type: "uint256",
      },
    ],
    name: "getStateById",
    outputs: [
      {
        internalType: "bool",
        name: "_found",
        type: "bool",
      },
      {
        internalType: "string",
        name: "_state",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_vcHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "extTimestamp",
        type: "uint256",
      },
    ],
    name: "getStatusByHash",
    outputs: [
      {
        internalType: "bool",
        name: "_found",
        type: "bool",
      },
      {
        internalType: "string",
        name: "_state",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_rat",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_uat",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_ext",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_nbf",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_vcHash",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "extTimestamp",
        type: "uint256",
      },
    ],
    name: "getStatusById",
    outputs: [
      {
        internalType: "bool",
        name: "_found",
        type: "bool",
      },
      {
        internalType: "string",
        name: "_state",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_rat",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_uat",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_ext",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_nbf",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_issuers",
        type: "address[]",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "issuer",
        type: "address",
      },
    ],
    name: "isCxcIssuer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_id",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "_vcHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_exp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_nbf",
        type: "uint256",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "ids",
        type: "bytes[]",
      },
      {
        internalType: "bytes32[]",
        name: "_vcHashes",
        type: "bytes32[]",
      },
      {
        internalType: "uint256[]",
        name: "_exp",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_nbf",
        type: "uint256[]",
      },
    ],
    name: "registerList",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_vcHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_exp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_nbf",
        type: "uint256",
      },
    ],
    name: "registerOnlyHash",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_vcHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "_reason",
        type: "string",
      },
    ],
    name: "revokeByHash",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_vcId",
        type: "bytes",
      },
      {
        internalType: "string",
        name: "_reason",
        type: "string",
      },
    ],
    name: "revokeById",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "_vcHashes",
        type: "bytes32[]",
      },
      {
        internalType: "string[]",
        name: "_reasons",
        type: "string[]",
      },
    ],
    name: "revokeListByHash",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "_vcIds",
        type: "bytes[]",
      },
      {
        internalType: "string[]",
        name: "_reasons",
        type: "string[]",
      },
    ],
    name: "revokeListById",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_vcHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_exp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_nbf",
        type: "uint256",
      },
    ],
    name: "updateByHash",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_vcId",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_exp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_nbf",
        type: "uint256",
      },
    ],
    name: "updateById",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IVCRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IVCRegistryInterface {
    return new utils.Interface(_abi) as IVCRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVCRegistry {
    return new Contract(address, _abi, signerOrProvider) as IVCRegistry;
  }
}
