/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVPRegistry,
  IVPRegistryInterface,
} from "../../../contracts/interfaces/IVPRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "verifier",
        type: "address",
      },
    ],
    name: "Consumed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
    ],
    name: "HashValid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "verifier",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "message0",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes15",
        name: "message1",
        type: "bytes15",
      },
    ],
    name: "NoStoragePolicy",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "verifier",
        type: "address",
      },
    ],
    name: "Presented",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address[10]",
        name: "to",
        type: "address[10]",
      },
    ],
    name: "Registered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint8",
        name: "prevState",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "uint8",
        name: "actualState",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "reason",
        type: "bytes32",
      },
    ],
    name: "StatusChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
    ],
    name: "cancel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
    ],
    name: "consumed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "extTimestamp",
        type: "uint256",
      },
    ],
    name: "getStatus",
    outputs: [
      {
        internalType: "bool",
        name: "found",
        type: "bool",
      },
      {
        components: [
          {
            internalType: "uint8",
            name: "state",
            type: "uint8",
          },
          {
            internalType: "address[10]",
            name: "allowedVerifiers",
            type: "address[10]",
          },
          {
            internalType: "address",
            name: "finalVerifier",
            type: "address",
          },
          {
            internalType: "bool",
            name: "valid",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "rat",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "uat",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "exp",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nbf",
            type: "uint256",
          },
        ],
        internalType: "struct VPStatus",
        name: "status",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
    ],
    name: "presented",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "vpHash",
        type: "bytes32",
      },
      {
        internalType: "address[10]",
        name: "allowedVerifiers",
        type: "address[10]",
      },
      {
        internalType: "uint256",
        name: "exp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nbf",
        type: "uint256",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IVPRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IVPRegistryInterface {
    return new utils.Interface(_abi) as IVPRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVPRegistry {
    return new Contract(address, _abi, signerOrProvider) as IVPRegistry;
  }
}
