/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Initializable } from "./@openzeppelin/contracts/proxy/utils/Initializable";
export { Initializable__factory } from "./factories/@openzeppelin/contracts/proxy/utils/Initializable__factory";
export type { IERC1822Proxiable } from "./contracts/external/openzeppelin/draft-IERC1822.sol/IERC1822Proxiable";
export { IERC1822Proxiable__factory } from "./factories/contracts/external/openzeppelin/draft-IERC1822.sol/IERC1822Proxiable__factory";
export type { ERC1967Proxy } from "./contracts/external/openzeppelin/ERC1967Proxy";
export { ERC1967Proxy__factory } from "./factories/contracts/external/openzeppelin/ERC1967Proxy__factory";
export type { ERC1967Upgrade } from "./contracts/external/openzeppelin/ERC1967Upgrade";
export { ERC1967Upgrade__factory } from "./factories/contracts/external/openzeppelin/ERC1967Upgrade__factory";
export type { IBeacon } from "./contracts/external/openzeppelin/IBeacon";
export { IBeacon__factory } from "./factories/contracts/external/openzeppelin/IBeacon__factory";
export type { Ownable } from "./contracts/external/openzeppelin/Ownable";
export { Ownable__factory } from "./factories/contracts/external/openzeppelin/Ownable__factory";
export type { Proxy } from "./contracts/external/openzeppelin/Proxy";
export { Proxy__factory } from "./factories/contracts/external/openzeppelin/Proxy__factory";
export type { ProxyAdmin } from "./contracts/external/openzeppelin/ProxyAdmin";
export { ProxyAdmin__factory } from "./factories/contracts/external/openzeppelin/ProxyAdmin__factory";
export type { TransparentUpgradeableProxy } from "./contracts/external/openzeppelin/TransparentUpgradeableProxy";
export { TransparentUpgradeableProxy__factory } from "./factories/contracts/external/openzeppelin/TransparentUpgradeableProxy__factory";
export type { IVCRegistry } from "./contracts/interfaces/IVCRegistry";
export { IVCRegistry__factory } from "./factories/contracts/interfaces/IVCRegistry__factory";
export type { IVPRegistry } from "./contracts/interfaces/IVPRegistry";
export { IVPRegistry__factory } from "./factories/contracts/interfaces/IVPRegistry__factory";
export type { VCRegistry } from "./contracts/VCRegistry";
export { VCRegistry__factory } from "./factories/contracts/VCRegistry__factory";
export type { VPRegistry } from "./contracts/VPRegistry";
export { VPRegistry__factory } from "./factories/contracts/VPRegistry__factory";
